# Generated by Django 5.0.4 on 2024-04-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('intereses', models.CharField(blank=True, max_length=100)),
                ('mensaje', models.TextField()),
                ('acepta_privacidad', models.BooleanField()),
            ],
        ),
    ]
