"""
Django settings for cliled project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
from decouple import config

X_FRAME_OPTIONS = 'SAMEORIGIN'


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%udo*7ofs+m)ad=0)96c#-(y$78co64l&mzc5$g0-^e)g_0&mm'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['14d7-2806-2f0-5501-e93a-2465-6fa3-bb7e-65b9.ngrok-free.app','6e11-2806-2f0-5501-e93a-f9f6-1166-3dfe-f540.ngrok-free.app', 'https://b49f-2806-2f0-5501-e93a-d1fd-e4eb-9838-99fb.ngrok-free.app/CliledWhatsapp/resultado','b49f-2806-2f0-5501-e93a-d1fd-e4eb-9838-99fb.ngrok-free.app','127.0.0.1', 'localhost','.vercel.app']

CORS_ORIGIN_WHITELIST = [
    'https://b49f-2806-2f0-5501-e93a-d1fd-e4eb-9838-99fb.ngrok-free.app',
    'https://6e11-2806-2f0-5501-e93a-f9f6-1166-3dfe-f540.ngrok-free.app',
    '6e11-2806-2f0-5501-e93a-f9f6-1166-3dfe-f540.ngrok-free.app',
    # Agrega otros orígenes confiables si es necesario
]

# Application definition

INSTALLED_APPS = [
    #'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'landingpage',
    
    'login',
    'registro',
    
    'extras',
    'crispy_forms',
    
    'django.contrib.postgres',
    'cliledcontactos',
    'cliledmensajes',
    
]

#Authentication backends


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'cliled.es.soporte@gmail.com'
EMAIL_HOST_PASSWORD = 'yecb yely qkcb avwi'
AUTH_USER_MODEL = 'registro.Usuario'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
]

ROOT_URLCONF = 'cliled.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cliled.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases






DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'postgres',
        'USER': 'postgres',
        'PASSWORD': 'gomitax222',
        'HOST': 'localhost',  # O la dirección IP de tu servidor PostgreSQL
        'PORT': '5432',       # Puerto predeterminado de PostgreSQL
      
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'es-es'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
