# Generated by Django 5.0.4 on 2024-04-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='tokens_disponibles',
            new_name='tokens_contactos',
        ),
        migrations.AddField(
            model_name='usuario',
            name='tokens_mensajes',
            field=models.IntegerField(default=20),
        ),
    ]
