# Generated by Django 5.0.4 on 2024-04-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_rename_tokens_disponibles_usuario_tokens_contactos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='contacos_enviado',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='mensajes_enviados',
            field=models.IntegerField(default=0),
        ),
    ]
