# Generated by Django 5.0.4 on 2024-04-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0004_usuario_licencia_12meses_usuario_licencia_3meses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='licencia_12meses',
            field=models.CharField(default=0),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='licencia_3meses',
            field=models.CharField(default=0),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='licencia_6meses',
            field=models.CharField(default=0),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='licencia_mes',
            field=models.CharField(default=0),
        ),
    ]
