# Generated by Django 5.0.4 on 2024-04-25 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0005_alter_usuario_licencia_12meses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='licencia_12meses_premium',
            field=models.CharField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='licencia_3meses_premium',
            field=models.CharField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='licencia_6meses_premium',
            field=models.CharField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='licencia_comprada',
            field=models.CharField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='licencia_mes_premium',
            field=models.CharField(default=0),
        ),
    ]
